<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "melos_rtb"
 *
 * Auto generated by Extension Builder 2014-12-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'melos - Ready to Build',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Marc Neuhaus',
	'author_email' => 'mneuhaus@famelo.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);